### ISSUE TITLE
Some MP3 files are reported to not play

### ISSUE THREAD

**Issue by deltabeard** [deltabeard/ctrmus#36]
A [user](https://gbatemp.net/threads/wip-ctrmus-another-3ds-music-player.454745/page-4) has reported that some MP3 files refuse to play. At least an error message should be shown with a reason as to why the file did not play.

**Comment by deltabeard** [comment]
Waiting for a sample MP3 file that doesn't work to test with.

**Comment by deltabeard** [comment]
I think there has been long enough opportunity for others to report issues with mp3 playback.

**Comment by Smoker1** [comment]
Always getting a Error 1000 when attempting to Play ANY .mp3 File.

**Comment by deltabeard** [comment]
Is it just mp3 files only or all files? This error message appears because DSP firmware needs to be dumped. You can use [this](https://gbatemp.net/threads/dsp1-a-new-dsp-dumper-cia-for-better-stability.469461/) program to dump it for you. After that, try ctrmus again.
