### ISSUE TITLE
Music plays for a few seconds and automatically stops itself.

### ISSUE THREAD

**Issue by Swampat** [deltabeard/ctrmus#38]
I trying to play a song and it starts to play as normal, then it stops itself automatically? Is it the file or the player?

**Comment by deltabeard** [comment]
Hi Swampat,

It could be either. If you know that the file should be playing longer than that, then it's an issue with the player.
What is the file type of the file?
Also, how long is the song meant to play?

**Comment by Swampat** [comment]
Its about 3 minutes and is a mp3 file

**Comment by deltabeard** [comment]
I haven't encountered this issue myself. Do you mind sending me the mp3 file to mk@deltabeard.com so that I can test possible fixes?
Do you only get the issue with this specific file?

Thanks.

**Comment by deltabeard** [comment]
Any update on this?

**Comment by Swampat** [comment]
Yeah fixed it sorry for not giving an update. :)
