### ISSUE TITLE
Garbled characters - Change to question mark?

### ISSUE THREAD

**Issue by kescherCode** [deltabeard/ctrmus#43]
Since non-ASCII characters are garbled, maybe a user-friendlier solution could be to change any characters exceeding ASCII to display as a question mark. This would prevent names with a lot of Unicode characters flooding the screen.

**Comment by deltabeard** [comment]
I wanted to fix this issue properly a couple of years ago by implementing a proper GUI that could display more characters, but I eventually lost interest and had little time to write such a thing. I'll leave this open in case I come back and add a work-around or write a GUI for ctrmus.

**Comment by fmlatghor** [comment]
Oh so a GUI was planned? I thought it was just the minimal interface or as I said in another issue, limitations. I don't understand this stuff, but I might spend some time in contributing if my code isn't awful.

**Comment by deltabeard** [comment]
@fmlatghor  You can use 2D and 3D graphics in 3DS homebrew. I chose to use the simple terminal interface to begin with, and then later planned on building a nice interface on top of it. But I never had the time or motivation.
The terminal interface is limited to only printing bitmap text.

**Comment by deltabeard** [comment]
This issue will be solved when the new UI is added, as it supports UTF-8. See https://github.com/deltabeard/ctrmus/issues/39.
