### ISSUE TITLE
Make a update with a few new features

### ISSUE THREAD

**Issue by PokemonBlackGamer** [deltabeard/ctrmus#45]
First add a background thats not black can be a flat color but add a color next make it to where you can show my folders on the screen  because I had to move the folder for ctrmus to see it. make d-pad down make the list go down or something

**Comment by N-SPC700** [comment]
I'm barely able to understand what you typed, please forgive me if I misinterpreted.

Anyways, here goes:
--
- Okay, so where was the folder where ctrmus couldn't see it? It has access to the entire SD card file structure. Did you possibly use "extra" characters, like Japanese characters or something? It'll still show, but with garbled characters.
- Are you not paying attention to the bottom screen? The bottom screen shows all the folders you can access, in blue text. White text is just a singular file. The top screen is just a "console log", where it just displays the actions you've taken (stopped a song, played another one, etc.)
- DPAD DOWN works fine for me, is your 3DS malfunctioning? Or did you happen to (somehow) install a broken version?
- The black background isn't that bad. This is a basic terminal interface, where all computers and systems print white text on a black background. There's really no reason to change the color, besides, what would it be changed to?

**Comment by fmlatghor** [comment]
> Did you possibly use "extra" characters, like Japanese characters or something?
If he were using unicode characters, he wouldn't have to move the file around.

> The black background isn't that bad. This is a basic terminal interface, where all computers and systems print white text on a black background. There's really no reason to change the color, besides, what would it be changed to?
I don't think it's bad, but I do wonder if there's some way to make the interface look better. I was wondering if it was a limitation; but I have no idea. I have no experience writing hacks for the 3ds.

**Comment by deltabeard** [comment]
Whatever problem there is with the interface should be fixed with the next update that introduces a graphic interface with full UTF-8 support.
