### ISSUE TITLE
MP3 files aren't working

### ISSUE THREAD

**Issue by MoistyTIT** [deltabeard/ctrmus#54]
I'm getting error 1002; I know these are mp3 files

**Comment by deltabeard** [comment]
Are you able to post one of these mp3 files for me to test?

**Comment by yeetboi-no-more** [comment]
Sure, no problem.  [Here it is.](https://drive.google.com/file/d/1MRhDlMIqE-lvyO7msTqyFDd9o2irw0Zi/view?usp=sharing)

**Comment by deltabeard** [comment]
The file seems to be corrupted (missing header?). `ffprobe` was unable to correctly display information on this file.

```
[mp3 @ 0000025519d38000] Format mp3 detected only with low score of 1, misdetection possible!
[mp3float @ 0000025519d39ac0] Header missing
    Last message repeated 564 times
[mp3 @ 0000025519d38000] decoding for stream 0 failed
[mp3 @ 0000025519d38000] Could not find codec parameters for stream 0 (Audio: mp3 (mp3float), 0 channels, fltp): unspecified frame size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, mp3, from 'When I Leave You.mp3':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: mp3, 0 channels, fltp
```

ffmpeg is unable to convert the file, and mpv (which uses ffmpeg) can't play the file either.

Does the file play in a different music player?

**Comment by deltabeard** [comment]
Since the file didn't play with ffmpeg, it probably wouldn't play with mpg123 either.
